// var a = 3;
// var b = prompt("what is your age");
// var c = Number(b);
// var d = a * c
// console.log(d);
// var a = 7;
// var b = 12;
// console.log(a < 12 && b > 10 && b != 12);
// var a = 10;
// var b = 11.67;
// var c = a + parseInt(b);
// console.log(c);
// var a = 10;
// var b = 11.67;
// var c = a + parseFloat(b);
// console.log(c);
// var a = 3;
// console.log(a == 6);
// console.log(a === 6);
// console.log(a != 6);
// console.log(a !== 6);
// console.log(a > 6);
// console.log(a < 6);
// console.log(a >= 6);
// console.log(a <= 6);
// &&
// var a = 5;
// var b = 6;
// var c = a < b && b < 10 && b == 6;
// console.log(c);
// ||
// a = 60;
// var b = a < 50 || a > 70;
// console.log(b);
// var c = 80;
// var d = c < 50 || c > 70;
// console.log(d);
// var a = 15;
// // var b = 5;
// var c = a < 10 || a > 20;
// console.log(c);
// var a = 60;
// var b = !(a < 50);
// alert(b);
// var c = 80;
// var d = !(c > 50);
// console.log(d);
// not!
// var a = 60;
// var b = a < 100;
// var c = !b;
// var d = !(a < 100);
// var e = !true;
// console.log("A = "+a);
// console.log("B = "+b);
// console.log("C = "+c);
// console.log("D = "+d);
// console.log("E = "+e);
// alert(!1);
// alert(!0);

// alert(!!45);
// alert(!!56)
var a = -6;
var b = !a;
var c = !!a;
console.log("A = "+a);
console.log("B = "+b);
console.log("C = "+c);
var a = 0;
var b = !a;
var c = !!a;
console.log("A = "+a);
console.log("B = "+b);
console.log("C = "+c);
var a = 6;
var b = !a;
var c = !!a;
console.log("A = "+a);
console.log("B = "+b);
console.log("C = "+c);
