// // var a = ["moiz",67,"helo"];
// // console.log(a);
// // console.log(a[0]);
// // console.log(a[2]);
// // a[0];
// // var foods=["mango","grapes","apple","banana"]
// // var a = foods[2];
// // console.log(a);
// // var nub=[1,2,3,4,5,6,7,8,9]
// // console.log(nub[0]);
// // console.log(nub[1]);
// // console.log(nub[2]);
// // console.log(nub[3]);
// // console.log(nub[4]);
// // var arr1 =[{name: "abdul moiz"},{fatherName: "zafar ali"}];
// // console.log(arr1[0]);
// // console.log(nub[9]);
// // console.log(foods[0]);
// // foods[0]="Orange";
// // console.log(foods[0]);
// // console.log(foods);
// // // foods[6]="lemon";
// // console.log(foods);
// // console.log(foods.length);
// // console.log(nub.length);
// // var arr1 = ["abdul moiz","Burger","Snacks"];
// // console.log(arr1);
// // arr1 [0]="abdul rafay";
// // console.log(arr1);
// // console.log(arr1[0]);
// // console.log(arr1[3]);
// // console.log(arr1.length);
// // var arr2=[];
// // console.log(arr2.length);
// var foods=[];
// foods.push("pizza");
// foods.push("Sandwich");
// foods.push("French Fries","chiense burger");
// foods.push("Snacks");
// foods.push("Banana");
// console.log(foods);
// console.log(foods[3]);
// console.log(foods[1]);
// console.log(foods.length);
// var foods =[];
// foods.push(prompt("Enter first food item"));
// foods.push(prompt("Enter second food item"));
// foods.push(prompt("Enter Third food item"));
// console.log(foods);
// console.log(foods[1]);
var arr1=[];
arr1.push(10);
arr1.push(9);
arr1.push(8);
arr1.push(7);
console.log(arr1[0]);
console.log(arr1);
