// alert("moiz");
// alert("hello world");
// console.log("hello world");
// console.log(2**9);
// console.log(34);
// document.write("hello JavaScript I am abdul moiz");
// document.write(2+388);
// var fullName = "abdul moiz";
// var age = 35;
// var isfeePaid = true;
// var weight;
// var a;
// console.log(fullName);
// console.log(age);
// age = 46;
// console.log(age);
// age = 88;
// console.log(age);
// console.log(isfeePaid);
// console.log(weight);
// // alert(fullName);
// console.log(a);
// var name = "abdu moiz";
// console.log(name);
// name = "khanzada";
// console.log(name);
// var message = "What is your name";
// console.log(message);
// console.log(name);
// var age = 56;
// var count = 34;
// count = 66;
// // alert(count);
// var a = 8;
// var b = 45;
// var c = a / b;
// console.log(a);
// console.log(b);
// console.log(c);
// var isfeePaid = true;
// isfeePaid = undefined;
// alert(isfeePaid);
// console.log(isfeePaid);
var name = null;
var nationality = "Pakistani"
console.log(null);
nationality = null;
console.log(nationality);