// // var name = "abdul moiz";
// // console.log(name);
// // var date = new Date();
// // console.log(date);
// // var a=date.getFullYear();
// // var b =date.getHours();
// // var c =date.getMinutes()
// // var d = date.getDay()
// // var e = date.getDate();
// // var f = date.getMonth();
// // console.log(a);
// // console.log(b);
// // console.log(c);
// // console.log(d);
// // console.log(e);
// // console.log(f);
// // console.log(date.getTime());
// // var dates = new Date("2020,05,20 14:30:01");
// // console.log(dates);
// // console.log(dates.getSeconds());
// // console.log(dates.getDate());
// // console.log(dates.getHours());
// // console.log(dates.getDay());
// // console.log(dates.getMilliseconds());
// // console.log(dates.setFullYear(2019));
// // console.log(dates);
// // console.log(dates.getMonth());
// var daysList = ["Sun","Mon","Tue","Wed","Thur","Fri","Sat"];
// console.log(daysList);
// var date = new Date("2020,05,20 14:30:01");
// console.log(date);
// var day = date.getDay();
// console.log(day);
// var listOfWeeks = daysList[day];
// console.log(listOfWeeks);
// // calcualte two diffrences
// var d1= new Date("June,10,2020 12:20:15");
// var d2= new Date("June,20,2020 12:20:15");
// // var d3 = new Date()
// // console.log(d3.getTime());
// var timeDiff = d2.getTime() - d1.getTime();
// console.log("Days Differnece ",timeDiff);
// console.log("Dtae 1",d1);
// console.log("Dtae 2",d2);
// var timeInDay = 24*60*60*1000;
// console.log(timeInDay);
// var daysDiffer = timeDiff/timeInDay;
// console.log(daysDiffer);
// var d3 = new Date();
// console.log(d3);
// console.log(d3.getTime());
// console.log(d1.setDate(15));
// console.log(d1);
var d1 = new Date("July,15,2020 12:10:30");
var d2 = new Date("July,15,2020 12:20:30");
var timeDiff = d2.getTime()-d1.getTime();
console.log(timeDiff);
var timeInDay = 24*60*60*1000;
console.log(timeInDay);
totalTime = timeDiff/timeInDay;
console.log(totalTime);