// var a = 6;
// var b = prompt("what is your score");
// var c = parseInt(b);
// console.log(a + c);
// var a = prompt("what is your number");
// var b = parseFloat(2);
// console.log(a *b);
// var a = 5;
// var b=prompt("what is your score");
// var c = Number(b);
// console.log(a+c);
// console.log(a*c);
var a = "8";
console.log(a==8);
console.log(a===8);
console.log(a!=8);
console.log(a>8);
console.log(a<8);
console.log(a>=8);
console.log(a<=8);
// console.log(a===8);
var a = 7;
var b = "5";
console.log(a == b);
console.log(a === b);
console.log(typeof a);
console.log(typeof b);
console.log(a != b);
console.log(a > b);
console.log(a < b);
console.log(a >= b);
console.log(a <= b);
