var a= 8;var b = 9;var c = a + b;
alert(a);alert(b);alert(c);
var a = 5
var b = 12
var c = a * b
console.log(c);
var sum = 3 / 9;
console.log(sum);
var a = 5;
a * 4;
console.log(a);
console.log(a*4);
var age = 56;
var age1 = 64;
var $age = 75;
var _age = 61;
var first_name = 32;
var my$world = "abdul moiz";
console.log($age);
console.log(_age);
console.log(my$world);  
var age = 45;
var _for = 54;
var $while = "moiz";
var name1 = "khanzada";
console.log(name1);
var a = 9;
var b = 7;

var c = a + b;
var d = a - b + 4 - 2;
var e = a * b;
var f = a / b;
var i = a % b;
var j = a ** b;
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(i);
console.log(j);
var a = 4;
a += 5;
console.log(a);
var a = 3 + 5 * 2;
var b = 8 / 2 -1;
var c = 3 % 2 + 4 - 1;
var d = a + 5 * c - b / (3 + b);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
var e = (3 * 13) - c / b ** d + d;
console.log(e);