// var a = 50;
// var b = prompt("what is your age");
// var c = parseInt(b);
// console.log(a + c);
// var a = 50;
// var b = prompt("what is your age");
// var c = parseFloat(b);
// console.log(a / c);
// var a = 50;
// var b = prompt("what is your age");
// var c = Number(b);
// console.log(a + c);
var a= "7";
var b;
console.log(a==7);
console.log(a===7);
console.log(a!=7);
console.log(a>7);
console.log(a<7);
console.log(a>=7);
console.log(a<=7);
console.log(typeof a);
console.log(typeof b);