// var a = 5 + 2 * (3 - 2) / 2;
// alert(a);
// console.log(a);
// var age = 34;
// console.log(age);
// var a =  6;
// a--;
// a++;
// a--;
// console.log(a);
// var a = 6;
// var b = ++a;
// console.log(a);
// console.log(b);
// var  a = 7;
// var b = a++;
// console.log(a);
// console.log(b);
// var  a = 7;
// var b = --a;
// console.log(a);
// console.log(b);
// var  a = 7;
// var b = a--;
// console.log(a);
// console.log(b);
// var  a = 8;
// var b = 3;
// // 9 - 3 + 9
// var c = a++ - b-- + --a;
// console.log(c);
// console.log(a);
// console.log(b);
// postfix increment
// var age = 12;
// var newAge = age++;
// alert(age);
// alert(newAge);
// prefix increment;
// var age = 12;
// var newAge = ++age;
// alert(age);
// alert(newAge);
// var a = 4;
// var b = 3;
// var c = a++ + --b - --a;
// console.log(a);
// console.log(b);
// console.log(c);
// var a = "6" + 2;
// alert(a);
// var b = 3 + "9";
// alert(b);
// var c = "Hello " + 2;
// alert(c);
// var d = 2 + "Hello ";
// alert(d);
// var e = "Hello "+ 3 + 4;
// alert(e)
// var f = 34 + "hello ";
// alert(f);
// var g = "hello " + (3 + 4);
// alert(g);
// prompt
var fullName = prompt("what is your name");
console.log(name);
var age = prompt("what is your age?");
console.log(age);